spring:
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    connection-timeout:
    channel-rpc-timeout:

  # swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: 8088
  #  port: 443
  servlet:
    context-path: /


# the target path , rap to json
json:
  # local share
  isShare: true
  # target path
  rootPath: /shareFile/apiJson
  # local share path
  sharePath: file://DESKTOP-B7C8MM8


url:
  # rap url
  rap: http://172.31.3.113:8080
  # rap2 url
  rap2: http://172.31.3.22:38080

# httpClient config
http:
  client:
    connect-timeout: 50000
    socket-timeout: 50000
    connection-request-timeout: 50000